name: CTFTime

on:
  schedule:
    - cron:  '2 2 */2 * *'
      ## run every 2nd day at 2:02
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ctftime_cache
          key: ${{ runner.os }}-ctftime-${{ hashFiles('ctftime_cache') }}
          restore-keys: |
            ${{ runner.os }}-ctftime-

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Run a one-line script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DiscordWebhookUrl }}
        run: |
          python -m pip install --upgrade pip
          pip install -r CTFtime-Discord-hooks/requirements.txt
          python CTFtime-Discord-hooks/CTFtimeDiscordHooks.py -w "$DISCORD_WEBHOOK_URL" -d 10 -c ctftime_cache